# Generated by https://quicktype.io
#
# To change quicktype's target language, run command:
#
#   "Set quicktype target language"
from dataclasses import dataclass
from enum import Enum
from typing import Dict


class AlarmMode(Enum):
    Disarmed = 0,
    FullArm = 1,
    HomeArm1 = 2,
    HomeArm2 = 3,
    HomeArm3 = 4


"""Wert auf AlarmModeAction parsen und dann nach AlarmMode casten"""


class AlarmModeAction(Enum):
    DISARM = 0,
    ARM_AWAY = 1,
    ARM_NIGHT = 2,
    ARM_HOME = 3


@dataclass(init=False)
class Pcondform:
    mode: AlarmMode
    f_arm: int


@dataclass(init=False)
class Forms:
    pcondform1: Pcondform
    pcondform2: Pcondform


@dataclass(init=False)
class PanelCondition:
    updates: Dict[str, str]
    forms: Forms
