# Generated by https://quicktype.io
#
# To change quicktype's target language, run command:
#
#   "Set quicktype target language"
from dataclasses import dataclass
from typing import List

from lupuxt2py.lupusec.dtos.actor import Actor


@dataclass(init=False)
class Pssrow(Actor):
    type: int
    name: str
    id: str
    status: str

    @property
    def identifier(self) -> str:
        return self.id

    @property
    def type_of(self) -> int:
        return self.type

    @property
    def state(self) -> str:
        return self.status

    @property
    def friendly_name(self) -> str:
        return self.name


@dataclass(init=False)
class PowerSwitchList:
    pssrows: List[Pssrow]
